/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run an iterative DNS trace */
        post: operations["createTrace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TraceRequest: {
            domain: string;
            /** @enum {string} */
            qtype: "A" | "AAAA" | "NS";
        };
        ErrorResponse: {
            error: string;
            message: string;
        };
        TraceResult: {
            trace_id: string;
            input_domain: string;
            normalized_domain: string;
            /** @enum {string} */
            qtype: "A" | "AAAA" | "NS";
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at: string;
            total_duration_ms: number;
            /** @enum {string} */
            status: "success" | "failure";
            final_outcome: components["schemas"]["FinalOutcome"];
            hops: components["schemas"]["Hop"][];
            summary: components["schemas"]["TraceSummary"];
            truth_notes: components["schemas"]["TruthNote"][];
        };
        TraceSummary: {
            headline: string;
            detail: string;
            total_hops: number;
            answer_count: number;
            cname_count: number;
        };
        FinalOutcome: {
            /** @enum {string} */
            kind: "success" | "nxdomain" | "servfail" | "timeout" | "refused" | "not_implemented" | "max_depth" | "unusable_referral" | "loop_detected";
            rcode: string;
            message: string;
            terminal_hop_index: number;
        };
        TruthNote: {
            code: string;
            message: string;
        };
        Hop: {
            index: number;
            parent_index?: number | null;
            /** @enum {string} */
            role: "root" | "tld" | "authoritative" | "alias" | "final" | "error";
            /** @enum {string} */
            hop_purpose: "delegation" | "nameserver_address_lookup" | "cname_follow";
            zone_context: string;
            server_name: string;
            server_ip: string;
            qname: string;
            qtype: string;
            /** @enum {string} */
            transport: "udp" | "tcp";
            latency_ms: number;
            response_code: string;
            authoritative: boolean;
            truncated: boolean;
            /** @enum {string} */
            response_kind: "referral" | "answer" | "cname" | "nodata" | "error";
            answer_rrsets: components["schemas"]["RRSet"][];
            authority_rrsets: components["schemas"]["RRSet"][];
            additional_rrsets: components["schemas"]["RRSet"][];
            next_targets: components["schemas"]["NextTarget"][];
            explanation: string;
            technical_note: string;
        };
        NextTarget: {
            server_name: string;
            server_ip: string;
            zone_context: string;
            reason: string;
        };
        RRSet: {
            /** @enum {string} */
            section: "answer" | "authority" | "additional";
            name: string;
            type: string;
            ttl: number;
            data: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createTrace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TraceRequest"];
            };
        };
        responses: {
            /** @description Trace completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceResult"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Method not allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
}
